package org.example
/*
 * This source file was generated by the Gradle 'init' task
 */

//class App {
//    fun main() {
//        print("asd")
//         val a = A1()
//         a.solution()
//    }
//}


