package org.example
/*
 * This source file was generated by the Gradle 'init' task
 */
import org.example.codingtest.level0.q1.A1

class App {
    fun main() {
        print("asd")
         val a = A1()
         a.solution()
    }
}


